version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - backend

  mlflow:
    build:
      context: ../docker
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@db:5432/mlflow
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    depends_on:
      - db
      - minio
    ports:
      - "5555:5000"
    networks:
      - backend

volumes:
  db_data:
  minio_data:

networks:
  backend:
    driver: bridge